name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y cmake g++ build-essential

      - name: Configure
        run: cmake -S . -B build

      - name: Build (Release)
        run: cmake --build build --config Release

      - name: Run tests (Release)
        run: |
          cd build/lib
          ./dywoqcxx_lib_tests
          cd ../runtime
          ./dywoqcxx_runtime_tests
          cd ../core
          ./dywoqcxx_core_tests
        shell: bash

      - name: Build (Debug)
        run: |
          cmake --build build --config Debug

      - name: Run tests (Debug)
        run: |
          cd build/lib
          ./dywoqcxx_lib_tests
          cd ../runtime
          ./dywoqcxx_runtime_tests
          cd ../core
          ./dywoqcxx_core_tests
        shell: bash
