name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: |
          sudo apt update
          sudo apt install clang-tidy

      - name: Run clang-tidy
        run: |
          cmake . -B build-tidy -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          find . -type f \( -name '*.cxx' -o -name '*.hxx' \) -print0 | xargs -0 clang-tidy --warnings-as-errors=*

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: |
          sudo apt update
          sudo apt install clang-format

      - name: Check formatting
        run: |
          find . -type f \( -name '*.cxx' -o -name '*.hxx' \) -print0 | xargs -0 clang-format --dry-run --Werror

  build-and-test:
    needs:
      - format-check
      - static-analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y cmake g++ build-essential

      - name: Build (Release and Debug)
        run: |
          cmake . -B build-release -DCMAKE_BUILD_TYPE=Release
          cmake . -B build-debug -DCMAKE_BUILD_TYPE=Debug
          cmake --build build-release
          cmake --build build-debug

      - name: Run tests (Debug)
        run: |
          ./build-debug/lib/dywoqcxx_lib_tests
          ./build-debug/runtime/dywoqcxx_runtime_tests
          ./build-debug/core/dywoqcxx_core_tests
        shell: bash

      - name: Run tests (Release)
        run: |
          ./build-release/lib/dywoqcxx_lib_tests
          ./build-release/runtime/dywoqcxx_runtime_tests
          ./build-release/core/dywoqcxx_core_tests
        shell: bash
