name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install tools (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y cmake g++ build-essential

      - name: Setup MSVC (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: |
          cmake -S . -B build \
          ${{ runner.os == 'Windows' || '' }}

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Tests
        run: |
          cd build

          # Linux
          if [ "$RUNNER_OS" = "Linux" ]; then
            cd lib
            ./dywoqstl_lib_tests
            cd ../runtime
            ./dywoqstl_runtime_tests
          fi

          # Windows
          if [ "$RUNNER_OS" = "Windows" ]; then
            cd lib/Release
            dywoqstl_lib_tests.exe
            cd ../../runtime/Release
            dywoqstl_runtime_tests.exe
          fi
        shell: bash
