name: CI

on:
  pull_request:
    branches: [main]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: |
          sudo apt update
          sudo apt install clang-format

      - name: Check formatting
        run: |
          find . -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' \) \
                      -print0 | xargs -0 clang-format --dry-run --Werror

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y cmake g++ build-essential

      - name: Build (Release and Debug)
        run: |
          cmake . -B build-release -DCMAKE_BUILD_TYPE=Release
          cmake . -B build-debug -DCMAKE_BUILD_TYPE=Debug
          cmake --build build-release
          cmake --build build-debug

      - name: Run tests (Debug)
        run: |
          cd build-debug/lib
          ./dywoqcxx_lib_tests
          cd ../runtime
          ./dywoqcxx_runtime_tests
          cd ../core
          ./dywoqcxx_core_tests
        shell: bash

      - name: Run tests (Release)
        run: |
          cd build-release/lib
          ./dywoqcxx_lib_tests
          cd ../runtime
          ./dywoqcxx_runtime_tests
          cd ../core
          ./dywoqcxx_core_tests
        shell: bash
