name: Core, Runtime and Standard Library

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: |
          sudo apt update
          sudo apt install clang-tidy

      - name: Run clang-tidy
        run: |
          cmake . -B build-tidy
          find . -type f \( -name '*.cxx' -o -name '*.hxx' \) -print0 | xargs -0 clang-tidy --warnings-as-errors=* -p build-tidy/

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: |
          sudo apt update
          sudo apt install clang-format

      - name: Check formatting
        run: |
          find . -type f \( -name '*.cxx' -o -name '*.hxx' \) -print0 | xargs -0 clang-format --dry-run --Werror

  build:
    needs:
      - format-check
      - static-analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential

      - name: Configuration (Release and Debug)
        run: |
          echo [RELEASE] Configuration
          cmake . -B build-release -DCMAKE_BUILD_TYPE=Release
          echo [DEBUG] Configuration
          cmake . -B build-debug -DCMAKE_BUILD_TYPE=Debug

      - name: Build (Release and Debug)
        run: |
          echo [RELEASE] Building
          cmake --build build-release
          echo [DEBUG] Building
          cmake --build build-debug
