name: Spark (test executor/framework)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.5'
        
    - name: Static analysis
      run: go vet ./...
      working-directory: ./tools/spark/
  
  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.5'
        
    - name: Format check
      run: gofmt -l .
      working-directory: ./tools/spark/
  
  build-and-test-executor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.5'

    - name: Build
      run: go build -v ./...
      working-directory: ./tools/spark/

    - name: Test
      run: go test -v ./...
      working-directory: ./tools/spark/
